-- MySQL Script generated by MySQL Workbench
-- Thu Jun 19 10:30:05 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema picket
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema picket
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `picket` DEFAULT CHARACTER SET utf8 ;
USE `picket` ;

-- -----------------------------------------------------
-- Table `picket`.`member_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `picket`.`member_role` (
  `id` INT NOT NULL,
  `name` VARCHAR(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `picket`.`member_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `picket`.`member_status` (
  `id` INT NOT NULL,
  `name` VARCHAR(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `picket`.`member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `picket`.`member` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(15) NULL,
  `email` VARCHAR(100) NULL,
  `password` VARCHAR(255) NULL,
  `nickname` VARCHAR(30) NULL,
  `member_role_id` INT NOT NULL,
  `member_status_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_member_member_role_idx` (`member_role_id` ASC) VISIBLE,
  INDEX `fk_member_member_status1_idx` (`member_status_id` ASC) VISIBLE,
  CONSTRAINT `fk_member_member_role`
    FOREIGN KEY (`member_role_id`)
    REFERENCES `picket`.`member_role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_member_member_status1`
    FOREIGN KEY (`member_status_id`)
    REFERENCES `picket`.`member_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `picket`.`place`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `picket`.`place` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(45) NULL,
  `postal_code` VARCHAR(10) NULL,
  `city` VARCHAR(50) NULL,
  `district` VARCHAR(50) NULL,
  `street` VARCHAR(100) NULL,
  `detail` VARCHAR(100) NULL,
  `created_date` TIMESTAMP NULL,
  `updated_date` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `picket`.`view_age`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `picket`.`view_age` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `picket`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `picket`.`product` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(45) NULL,
  `place_id` BIGINT NOT NULL,
  `view_age_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_place1_idx` (`place_id` ASC) VISIBLE,
  INDEX `fk_product_view_age1_idx` (`view_age_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_place1`
    FOREIGN KEY (`place_id`)
    REFERENCES `picket`.`place` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_view_age1`
    FOREIGN KEY (`view_age_id`)
    REFERENCES `picket`.`view_age` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `picket`.`payment_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `picket`.`payment_type` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `picket`.`payment_state`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `picket`.`payment_state` (
  `id` INT NOT NULL,
  `name` VARCHAR(30) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `picket`.`seat_grade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `picket`.`seat_grade` (
  `id` INT NOT NULL,
  `name` VARCHAR(10) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `picket`.`seat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `picket`.`seat` (
  `id` INT NOT NULL,
  `grade` VARCHAR(45) NULL,
  `row` VARCHAR(45) NULL,
  `col` VARCHAR(45) NULL,
  `place_id` BIGINT NOT NULL,
  `seat_grade_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_seat_place1_idx` (`place_id` ASC) VISIBLE,
  INDEX `fk_seat_seat_grade1_idx` (`seat_grade_id` ASC) VISIBLE,
  CONSTRAINT `fk_seat_place1`
    FOREIGN KEY (`place_id`)
    REFERENCES `picket`.`place` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_seat_seat_grade1`
    FOREIGN KEY (`seat_grade_id`)
    REFERENCES `picket`.`seat_grade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `picket`.`ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `picket`.`ticket` (
  `id` BIGINT NOT NULL,
  `member_id` BIGINT NOT NULL,
  `product_id` BIGINT NOT NULL,
  `payment_type_id` INT NOT NULL,
  `payment_state_id` INT NOT NULL,
  `seat_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_member_has_product_product1_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_member_has_product_member1_idx` (`member_id` ASC) VISIBLE,
  INDEX `fk_ticket_payment_type1_idx` (`payment_type_id` ASC) VISIBLE,
  INDEX `fk_ticket_payment_state1_idx` (`payment_state_id` ASC) VISIBLE,
  INDEX `fk_ticket_seat1_idx` (`seat_id` ASC) VISIBLE,
  CONSTRAINT `fk_member_has_product_member1`
    FOREIGN KEY (`member_id`)
    REFERENCES `picket`.`member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_member_has_product_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `picket`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_payment_type1`
    FOREIGN KEY (`payment_type_id`)
    REFERENCES `picket`.`payment_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_payment_state1`
    FOREIGN KEY (`payment_state_id`)
    REFERENCES `picket`.`payment_state` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_seat1`
    FOREIGN KEY (`seat_id`)
    REFERENCES `picket`.`seat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `picket`.`card_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `picket`.`card_info` (
  `id` BIGINT NOT NULL,
  `card_number` VARCHAR(45) NULL,
  `CVC` CHAR(3) NULL,
  `expired_date` CHAR(5) NULL,
  `password` CHAR(2) NULL,
  `member_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_card_info_member1_idx` (`member_id` ASC) VISIBLE,
  CONSTRAINT `fk_card_info_member1`
    FOREIGN KEY (`member_id`)
    REFERENCES `picket`.`member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `picket`.`payment_cancel_wait`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `picket`.`payment_cancel_wait` (
  `id` BIGINT NOT NULL,
  `created_time` TIMESTAMP NULL,
  `ticket_id` BIGINT NOT NULL,
  `seat_grade_id` INT NOT NULL,
  `card_info_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_payment_cancel_wait_ticket1_idx` (`ticket_id` ASC) VISIBLE,
  INDEX `fk_payment_cancel_wait_seat_grade1_idx` (`seat_grade_id` ASC) VISIBLE,
  INDEX `fk_payment_cancel_wait_card_info1_idx` (`card_info_id` ASC) VISIBLE,
  CONSTRAINT `fk_payment_cancel_wait_ticket1`
    FOREIGN KEY (`ticket_id`)
    REFERENCES `picket`.`ticket` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_payment_cancel_wait_seat_grade1`
    FOREIGN KEY (`seat_grade_id`)
    REFERENCES `picket`.`seat_grade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_payment_cancel_wait_card_info1`
    FOREIGN KEY (`card_info_id`)
    REFERENCES `picket`.`card_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `picket`.`review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `picket`.`review` (
  `id` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `content` VARCHAR(45) NULL,
  `score` FLOAT NULL,
  `created_time` TIMESTAMP NULL,
  `img_path` VARCHAR(45) NULL,
  `product_id` BIGINT NOT NULL,
  `member_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_review_product1_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_review_member1_idx` (`member_id` ASC) VISIBLE,
  CONSTRAINT `fk_review_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `picket`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_review_member1`
    FOREIGN KEY (`member_id`)
    REFERENCES `picket`.`member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `picket`.`qna`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `picket`.`qna` (
  `id` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `content` VARCHAR(45) NULL,
  `created_date` TIMESTAMP NULL,
  `product_id` BIGINT NOT NULL,
  `member_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_qna_product1_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_qna_member1_idx` (`member_id` ASC) VISIBLE,
  CONSTRAINT `fk_qna_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `picket`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_qna_member1`
    FOREIGN KEY (`member_id`)
    REFERENCES `picket`.`member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `picket`.`reply`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `picket`.`reply` (
  `id` BIGINT NOT NULL,
  `created_date` TIMESTAMP NULL,
  `title` VARCHAR(45) NULL,
  `content` VARCHAR(45) NULL,
  `qna_id` INT NOT NULL,
  `member_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reply_qna1_idx` (`qna_id` ASC) VISIBLE,
  INDEX `fk_reply_member1_idx` (`member_id` ASC) VISIBLE,
  CONSTRAINT `fk_reply_qna1`
    FOREIGN KEY (`qna_id`)
    REFERENCES `picket`.`qna` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reply_member1`
    FOREIGN KEY (`member_id`)
    REFERENCES `picket`.`member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
